version: '3.9'

services:
  google_main_react:
    image: registry.dev.home/node:19.9.0
    container_name: google_main_react
    environment:
      VIRTUAL_HOST: googleclone.dev.home
    networks:
      - devnet
    working_dir: /app
    volumes:
      - /media/adam/DOCKER/BASIC_IMAGES/OPENSSL_CERTS/dev.home/:/ssl-certs/:ro
      - .:/app:rw
    ports:
      - "3000"
    entrypoint: ["bash", "-c"]
    command: ["yarn start"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"




networks:
  devnet:
    external: true 
